// <auto-generated />
namespace BurgerJoint.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class save : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(save));
        
        string IMigrationMetadata.Id
        {
            get { return "202111271411481_save"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
